# Generated by Django 4.1.5 on 2023-03-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thinkific_User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('roles', models.JSONField(default=list)),
                ('avatar_url', models.URLField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliate_code', models.CharField(blank=True, max_length=255, null=True)),
                ('external_source', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliate_commission', models.DecimalField(decimal_places=2, max_digits=5)),
                ('affiliate_commission_type', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliate_payout_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('administered_course_ids', models.JSONField(blank=True, default=list, null=True)),
                ('custom_profile_fields', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'verbose_name': 'Thinkific User',
                'managed': True,
            },
        ),
    ]
