# Generated by Django 4.1.5 on 2023-03-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkific', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thinkific_user',
            name='roles',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
