# Generated by Django 4.1.5 on 2023-03-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkific', '0003_alter_thinkific_user_affiliate_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thinkific_user',
            name='administered_course_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thinkific_user',
            name='custom_profile_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
