# Generated by Django 4.1.5 on 2023-03-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkific', '0004_alter_thinkific_user_administered_course_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thinkific_Users_Enrollments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.IntegerField(blank=True, max_length=255, null=True)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('course_id', models.IntegerField(blank=True, max_length=255, null=True)),
                ('percentage_completed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('expired', models.BooleanField(default=False)),
                ('is_free_trial', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Thinkific Users Enrollments',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='thinkific_user',
            options={'managed': True, 'verbose_name': 'Thinkific Users'},
        ),
    ]
