# Generated by Django 4.1.5 on 2023-03-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkific', '0005_thinkific_users_enrollments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thinkific_users_enrollments',
            name='course_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thinkific_users_enrollments',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
