# Generated by Django 4.1.5 on 2023-04-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkific', '0007_rename_completed_thinkific_users_enrollments_free_trial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thinkific_users_enrollments',
            old_name='free_trial',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='thinkific_users_enrollments',
            name='course_details',
        ),
        migrations.RemoveField(
            model_name='thinkific_users_enrollments',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='thinkific_users_enrollments',
            name='user_details',
        ),
        migrations.AddField(
            model_name='thinkific_users_enrollments',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thinkific_users_enrollments',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thinkific_users_enrollments',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thinkific_users_enrollments',
            name='is_free_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thinkific_users_enrollments',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thinkific_users_enrollments',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
