# Generated by Django 4.1.5 on 2023-04-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkific', '0009_rename_completed_thinkific_users_enrollments_free_trial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thinkific_users_enrollments',
            name='course_details',
        ),
        migrations.RemoveField(
            model_name='thinkific_users_enrollments',
            name='user_details',
        ),
        migrations.AddField(
            model_name='thinkific_users_enrollments',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thinkific_users_enrollments',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thinkific_users_enrollments',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thinkific_users_enrollments',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thinkific_users_enrollments',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
