# Generated by Django 4.1.5 on 2023-04-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thinkific', '0010_remove_thinkific_users_enrollments_course_details_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thinkific_user',
            options={'managed': True, 'verbose_name': 'Thinkific User'},
        ),
        migrations.AlterModelOptions(
            name='thinkific_users_enrollments',
            options={'managed': True, 'verbose_name': 'Thinkific Users Enrollment'},
        ),
    ]
