# Generated by Django 4.1.5 on 2023-07-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thinkific', '0011_alter_thinkific_user_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thinkific_users_enrollments',
            old_name='user_id',
            new_name='thinkific_user_id',
        ),
    ]
