# Generated by Django 4.1.5 on 2023-07-17 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thinkific', '0012_rename_user_id_thinkific_users_enrollments_thinkific_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thinkific_users_enrollments',
            name='thinkific_user_id',
        ),
        migrations.AddField(
            model_name='thinkific_users_enrollments',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_enrollments', to='thinkific.thinkific_user'),
        ),
    ]
