# Generated by Django 4.1.5 on 2023-07-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkific', '0013_remove_thinkific_users_enrollments_thinkific_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thinkific_user',
            name='erp_lead_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
