# Generated by Django 4.1.5 on 2023-07-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkific', '0015_alter_thinkific_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='thinkific_users_enrollments',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
