# Generated by Django 4.1.5 on 2023-07-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkific', '0016_thinkific_users_enrollments_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thinkific_users_enrollments',
            name='phone',
        ),
        migrations.AddField(
            model_name='thinkific_user',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
