# Generated by Django 4.1.5 on 2023-11-16 06:59
# Generated by Django 4.1.5 on 2023-11-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkific', '0017_remove_thinkific_users_enrollments_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thinkific_users_enrollments',
            name='status',
            field=models.CharField(default='In Progress', max_length=200),
        ),
    ]
