# Generated by Django 4.1.5 on 2023-12-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkific', '0018_thinkific_users_enrollments_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thinkific_users_enrollments',
            name='status',
        ),
        migrations.AddField(
            model_name='thinkific_users_enrollments',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thinkific_users_enrollments',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
