# Generated by Django 4.1.5 on 2023-05-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_main_product_trainers'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='products.main_product'),
        ),
    ]
