# Generated by Django 4.1.5 on 2023-05-31 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_main_product_trainers'),
        ('trainers', '0002_alter_trainer_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='products',
            field=models.ManyToManyField(to='products.main_product'),
        ),
    ]
