# Generated by Django 4.1.5 on 2023-06-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_remove_affiliateuniqueclick_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateuser',
            name='erp_lead_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
