# Generated by Django 4.1.5 on 2023-06-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0005_affiliateuser_accept_aggrement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateuniqueclick',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='affiliateuser',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
