# Generated by Django 4.1.5 on 2023-07-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0006_affiliateuniqueclick_source_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateuser',
            name='email',
            field=models.EmailField(default='no email', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
