# Generated by Django 4.1.5 on 2023-08-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0008_affiliateleads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AffiliateLeads',
            new_name='AffiliateLead',
        ),
    ]
