# Generated by Django 4.1.5 on 2023-08-01 10:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0009_rename_affiliateleads_affiliatelead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('product', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('amount_pkr', models.IntegerField(default=0)),
                ('amount_usd', models.IntegerField(default=0)),
                ('commission_usd', models.CharField(default=0, max_length=30)),
                ('commission_pkr', models.CharField(default=0, max_length=30)),
                ('student_email', models.CharField(max_length=150)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('affiliate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_user', to='affiliate.affiliateuser')),
            ],
        ),
    ]
