# Generated by Django 4.1.5 on 2023-08-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0010_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliateuniqueclick',
            name='source_id',
        ),
        migrations.AlterField(
            model_name='affiliateuniqueclick',
            name='ip',
            field=models.CharField(default='noip', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
