# Generated by Django 4.1.5 on 2023-08-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0011_remove_affiliateuniqueclick_source_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliateuniqueclick',
            old_name='affiliate_id',
            new_name='affiliate',
        ),
    ]
