# Generated by Django 4.1.5 on 2023-08-02 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0012_rename_affiliate_id_affiliateuniqueclick_affiliate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateuniqueclick',
            name='affiliate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_clicks', to='affiliate.affiliateuser'),
        ),
        migrations.AlterField(
            model_name='affiliateuser',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='affiliate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_commission', to='affiliate.affiliateuser'),
        ),
    ]
