# Generated by Django 4.1.5 on 2023-08-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0013_alter_affiliateuniqueclick_affiliate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliateuser',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='affiliatelead',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affiliateuniqueclick',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affiliateuser',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
