# Generated by Django 4.1.5 on 2023-08-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0014_remove_affiliateuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
