# Generated by Django 4.1.5 on 2023-01-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_source', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('enrollment_name', models.CharField(max_length=50)),
                ('enrollment_creation_date', models.DateTimeField(auto_now_add=True)),
                ('enrollment_expiry_date', models.DateTimeField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
