# Generated by Django 4.1.5 on 2023-01-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='enrollment_creation_date',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='enrollment_expiry_date',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
