# Generated by Django 4.1.5 on 2023-01-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_enrollment_creation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='enrollment_creation_date',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='enrollment_expiry_date',
            new_name='country',
        ),
    ]
