# Generated by Django 4.1.5 on 2023-02-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_enrollment_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='enrollment_creation_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='enrollment_expiry_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='enrollment_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_source',
        ),
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='created',
            field=models.DateTimeField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
