# Generated by Django 4.1.5 on 2023-03-26 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_stripe_payment_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripe_payment',
            name='customer_email',
        ),
    ]
