# Generated by Django 4.1.5 on 2023-02-02 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_payment_enrollment_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'managed': False},
        ),
    ]
