# Generated by Django 4.1.5 on 2023-02-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='automated_payments',
        ),
    ]
