# Generated by Django 4.1.5 on 2023-03-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_stripe_payment_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripe_payment',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
