# Generated by Django 4.1.5 on 2023-02-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Easypaisa_Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ops_id', models.CharField(blank=True, max_length=50, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('order_date', models.CharField(blank=True, max_length=50, null=True)),
                ('order_time', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_msidn', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('amount_PKR', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_card', models.CharField(blank=True, max_length=50, null=True)),
                ('bin_bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('fee_pkr', models.CharField(blank=True, max_length=50, null=True)),
                ('fed_pkr', models.CharField(blank=True, max_length=50, null=True)),
                ('error_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('token_paid_date', models.CharField(blank=True, max_length=50, null=True)),
                ('token_paid_time', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
