# Generated by Django 4.1.5 on 2023-02-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_easypaisa_payments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Easypaisa_Payments',
            new_name='Easypaisa_Payment',
        ),
    ]
