# Generated by Django 4.1.5 on 2023-02-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_rename_easypaisa_payments_easypaisa_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='easypaisa_payment',
            options={'managed': False},
        ),
    ]
