# Generated by Django 4.1.5 on 2023-03-27 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_stripe_payment_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlNafi_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField(null=True)),
                ('customer_email', models.CharField(max_length=100, null=True)),
                ('product_name', models.CharField(max_length=50, null=True)),
                ('amount_pkr', models.IntegerField(default=0)),
                ('amount_usd', models.IntegerField(default=0)),
                ('order_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('expiration_datetime', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('order_id', models.CharField(max_length=50, null=True)),
                ('date_of_activation', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('qarz', models.BooleanField(default=False)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('payment_proof', models.CharField(max_length=100, null=True)),
                ('send_invoice', models.BooleanField(blank=True, default=True, null=True)),
                ('pk_invoice_number', models.CharField(blank=True, max_length=10, null=True)),
                ('us_invoice_number', models.CharField(blank=True, max_length=10, null=True)),
                ('sponsored', models.BooleanField(default=False)),
                ('coupon_code', models.CharField(max_length=20, null=True)),
                ('is_upgrade_payment', models.BooleanField(default=False)),
                ('affiliate', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Al-Nafi Payment',
                'ordering': ['-order_datetime'],
                'managed': True,
            },
        ),
    ]
