# Generated by Django 4.1.5 on 2023-02-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_easypaisa_payment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UBL_IPG_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(max_length=254)),
                ('card_mask', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('order_datetime', models.DateTimeField(max_length=60)),
                ('order_id', models.CharField(max_length=100)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('captured', models.CharField(blank=True, max_length=50, null=True)),
                ('reversed', models.CharField(blank=True, max_length=50, null=True)),
                ('refund', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_code', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ubl_ipg_payments',
                'managed': True,
            },
        ),
        migrations.AlterModelTable(
            name='easypaisa_payment',
            table='easypaisa_payments',
        ),
    ]
