# Generated by Django 4.1.5 on 2023-02-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_ubl_ipg_payment_alter_easypaisa_payment_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubl_ipg_payment',
            options={'managed': False},
        ),
    ]
