# Generated by Django 4.1.5 on 2023-03-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alnafi_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UBL_Manual_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=50, null=True)),
                ('depositor_name', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('order_datetime', models.DateField(blank=True, max_length=50, null=True)),
                ('activation_datetime', models.DateField(blank=True, max_length=50, null=True)),
                ('payment_channel', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('s3_file_url', models.CharField(blank=True, max_length=50, null=True)),
                ('s3_file_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'UBL-Manual Payment',
                'ordering': ['-order_datetime'],
                'managed': True,
            },
        ),
    ]
