# Generated by Django 4.1.5 on 2023-02-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_ubl_ipg_payment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='easypaisa_payment',
            options={'managed': False, 'verbose_name': 'Easypaisa Payments'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'managed': False, 'verbose_name': 'Stripe Payments'},
        ),
        migrations.AlterModelOptions(
            name='ubl_ipg_payment',
            options={'managed': False, 'verbose_name': 'UBL IPG Payments'},
        ),
    ]
