# Generated by Django 4.1.5 on 2023-02-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_dripscheduling_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='courses',
        ),
        migrations.DeleteModel(
            name='DripScheduling',
        ),
    ]
