# Generated by Django 4.1.5 on 2023-04-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_remove_navbarlink_slug_navbarlink_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarlink',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
