# Generated by Django 4.1.5 on 2023-05-08 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_main_user'),
        ('products', '0024_main_product_amount_gbp_main_product_bundle_ids_and_more'),
        ('payment', '0014_navbarlink_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_pyament_id', models.CharField(blank=True, max_length=100, null=True)),
                ('alnafi_pyament_id', models.CharField(blank=True, max_length=50, null=True)),
                ('easypaisa_ops_id', models.CharField(blank=True, max_length=50, null=True)),
                ('easypaisa_customer_msidn', models.CharField(blank=True, max_length=50, null=True)),
                ('card_mask', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('order_datetime', models.DateTimeField(blank=True, null=True)),
                ('expiration_datetime', models.DateTimeField(blank=True, null=True)),
                ('activation_datetime', models.DateTimeField(blank=True, null=True)),
                ('token_paid_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('easypaisa_fee_pkr', models.CharField(blank=True, max_length=50, null=True)),
                ('easypaisa_fed_pkr', models.CharField(blank=True, max_length=50, null=True)),
                ('ubl_captured', models.CharField(blank=True, max_length=50, null=True)),
                ('ubl_reversed', models.CharField(blank=True, max_length=50, null=True)),
                ('ubl_refund', models.CharField(blank=True, max_length=50, null=True)),
                ('ubl_approval_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('qarz', models.BooleanField(default=False)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('payment_proof', models.CharField(max_length=100, null=True)),
                ('send_invoice', models.BooleanField(blank=True, default=True, null=True)),
                ('pk_invoice_number', models.CharField(blank=True, max_length=10, null=True)),
                ('us_invoice_number', models.CharField(blank=True, max_length=10, null=True)),
                ('sponsored', models.BooleanField(default=False)),
                ('coupon_code', models.CharField(max_length=20, null=True)),
                ('is_upgrade_payment', models.BooleanField(default=False)),
                ('affiliate', models.CharField(max_length=50, null=True)),
                ('s3_file_url', models.CharField(blank=True, max_length=600, null=True)),
                ('s3_file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('ubl_depositor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('ubl_payment_channel', models.CharField(blank=True, max_length=45, null=True)),
                ('bin_bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('error_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Payment_Product', to='products.main_product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Payment_User', to='user.main_user')),
            ],
        ),
    ]
