# Generated by Django 4.1.5 on 2023-03-09 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_remove_product_courses_delete_dripscheduling'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
