# Generated by Django 4.1.5 on 2023-05-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_alter_main_payment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_payment',
            name='source',
            field=models.CharField(blank=True, choices=[('Easypaisa', 'Easypaisa'), ('Stripe', 'Stripe'), ('AlnafiMain', 'AlnafiMain'), ('UBLIPG', 'UBLIPG'), ('UBLMANUAL', 'UBLMANUAL')], max_length=50, null=True),
        ),
    ]
