# Generated by Django 4.1.5 on 2023-03-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
