# Generated by Django 4.1.5 on 2023-03-21 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_delete_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='easypaisa_payment',
            options={'managed': False, 'ordering': ['-order_datetime'], 'verbose_name': 'Easypaisa Payment'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'managed': False, 'ordering': ['-created'], 'verbose_name': 'Stripe Payment'},
        ),
        migrations.AlterModelOptions(
            name='ubl_ipg_payment',
            options={'managed': False, 'ordering': ['-order_datetime'], 'verbose_name': 'UBL IPG Payment'},
        ),
    ]
