# Generated by Django 4.1.5 on 2023-05-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_alter_main_payment_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_payment',
            old_name='source_pyament_id',
            new_name='source_payment_id',
        ),
    ]
