# Generated by Django 4.1.5 on 2023-03-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_alter_easypaisa_payment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stripe_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('order_datetime', models.DateTimeField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Stripe Payment',
                'ordering': ['-order_datetime'],
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AlterModelOptions(
            name='easypaisa_payment',
            options={'managed': True, 'ordering': ['-order_datetime'], 'verbose_name': 'Easypaisa Payment'},
        ),
        migrations.AlterModelOptions(
            name='ubl_ipg_payment',
            options={'managed': True, 'ordering': ['-order_datetime'], 'verbose_name': 'UBL IPG Payment'},
        ),
    ]
