# Generated by Django 4.1.5 on 2023-05-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_rename_source_pyament_id_main_payment_source_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_payment',
            old_name='alnafi_pyament_id',
            new_name='alnafi_payment_id',
        ),
    ]
