# Generated by Django 4.1.5 on 2023-05-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_rename_alnafi_pyament_id_main_payment_alnafi_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_payment',
            old_name='product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='main_payment',
            old_name='user',
            new_name='user',
        ),
    ]
