# Generated by Django 4.1.5 on 2023-05-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_rename_product_id_main_payment_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_payment',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
