# Generated by Django 4.1.5 on 2023-05-16 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_main_user_is_paying_customer'),
        ('payment', '0023_alter_main_payment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_payments', to='user.main_user'),
        ),
    ]
