# Generated by Django 4.1.5 on 2023-05-30 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_alter_main_payment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubl_manual_payment',
            options={'managed': True, 'ordering': ['-deposit_date'], 'verbose_name': 'UBL-Manual Payment'},
        ),
        migrations.RemoveField(
            model_name='ubl_manual_payment',
            name='activation_datetime',
        ),
        migrations.RemoveField(
            model_name='ubl_manual_payment',
            name='order_datetime',
        ),
        migrations.RemoveField(
            model_name='ubl_manual_payment',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='ubl_manual_payment',
            name='s3_file_name',
        ),
        migrations.RemoveField(
            model_name='ubl_manual_payment',
            name='s3_file_url',
        ),
        migrations.AddField(
            model_name='ubl_manual_payment',
            name='candidate_phone',
            field=models.CharField(blank=True, default='', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='ubl_manual_payment',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='ubl_manual_payment',
            name='deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ubl_manual_payment',
            name='transaction_image',
            field=models.CharField(blank=True, default='', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='amount',
            field=models.CharField(blank=True, default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='candidate_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='customer_email',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='depositor_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='payment_channel',
            field=models.CharField(blank=True, default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='source',
            field=models.CharField(blank=True, default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='status',
            field=models.CharField(blank=True, default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=45, null=True),
        ),
    ]
