# Generated by Django 4.1.5 on 2023-05-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_alter_ubl_manual_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='deposit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
