# Generated by Django 4.1.5 on 2023-05-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_alter_ubl_manual_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='transaction_image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
