# Generated by Django 4.1.5 on 2023-05-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_alter_ubl_manual_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='transaction_image',
            field=models.FileField(blank=True, null=True, upload_to='UBL-manual-payment-receipts'),
        ),
    ]
