# Generated by Django 4.1.5 on 2023-05-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_alter_ubl_manual_payment_transaction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='candidate_phone',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='customer_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='depositor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='payment_channel',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='source',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
