# Generated by Django 4.1.5 on 2023-06-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_alter_ubl_manual_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_payment',
            name='s3_file_name',
        ),
        migrations.RemoveField(
            model_name='main_payment',
            name='s3_file_url',
        ),
        migrations.AddField(
            model_name='main_payment',
            name='internal_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='main_payment',
            name='payment_proof',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
