# Generated by Django 4.1.5 on 2023-06-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0028_remove_main_payment_s3_file_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_payment',
            old_name='ubl_payment_channel',
            new_name='ubl_candidate_phone',
        ),
        migrations.AddField(
            model_name='main_payment',
            name='ubl_candidate_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
