# Generated by Django 4.1.5 on 2023-06-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0030_stripe_payment_alnafi_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_payment',
            old_name='ubl_candidate_name',
            new_name='candidate_name',
        ),
        migrations.RenameField(
            model_name='main_payment',
            old_name='ubl_candidate_phone',
            new_name='candidate_phone',
        ),
    ]
