# Generated by Django 4.1.5 on 2023-06-19 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_main_user_internal_source'),
        ('payment', '0031_rename_ubl_candidate_name_main_payment_candidate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_payments', to='user.main_user'),
        ),
    ]
