# Generated by Django 4.1.5 on 2023-07-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0032_alter_main_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alnafi_payment',
            name='affiliate',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='alnafi_payment',
            name='coupon_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='alnafi_payment',
            name='customer_email',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='alnafi_payment',
            name='order_id',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='alnafi_payment',
            name='payment_proof',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='alnafi_payment',
            name='pk_invoice_number',
            field=models.CharField(blank=True, max_length=101, null=True),
        ),
        migrations.AlterField(
            model_name='alnafi_payment',
            name='product_name',
            field=models.CharField(max_length=330, null=True),
        ),
        migrations.AlterField(
            model_name='alnafi_payment',
            name='remarks',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='alnafi_payment',
            name='source',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='alnafi_payment',
            name='us_invoice_number',
            field=models.CharField(blank=True, max_length=101, null=True),
        ),
        migrations.AlterField(
            model_name='stripe_payment',
            name='customer_email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='stripe_payment',
            name='product_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_ipg_payment',
            name='product_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
