# Generated by Django 4.1.5 on 2023-07-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0033_alter_alnafi_payment_affiliate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alnafi_payment',
            name='affiliate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='alnafi_payment',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='alnafi_payment',
            name='date_of_activation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alnafi_payment',
            name='payment_proof',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='alnafi_payment',
            name='remarks',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
