# Generated by Django 4.1.5 on 2023-07-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0035_alter_ubl_manual_payment_payment_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alnafi_payment',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='main_payment',
            name='remarks',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
