# Generated by Django 4.1.5 on 2023-07-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0036_alter_alnafi_payment_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='transaction_id',
            field=models.CharField(default='noid', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
