# Generated by Django 4.1.5 on 2023-07-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_alter_alnafi_user_email'),
        ('payment', '0038_alter_main_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_payments', to='user.main_user'),
        ),
    ]
