# Generated by Django 4.1.5 on 2023-08-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0039_alter_main_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alnafi_payment',
            name='payment_id',
            field=models.IntegerField(null=True, unique=False),
        ),
    ]
