# Generated by Django 4.1.5 on 2023-09-22 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0042_alter_alnafi_payment_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Al_Nafi_Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('affiliate_code', models.CharField(blank=True, max_length=200, null=True)),
                ('coupon_id', models.CharField(blank=True, max_length=200, null=True)),
                ('application', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=200, null=True)),
                ('product_ids', models.JSONField(null=True)),
                ('product_data', models.JSONField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('orderId', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('amount_pkr', models.IntegerField(blank=True, null=True)),
                ('amount_usd', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(default='US', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('paid', 'Paid'), ('not_enough_balance', 'Not Enough Balance'), ('cancelled', 'Cancelled'), ('incorrect_details', 'Incorrect Details'), ('inactive_account', 'Inactive Account'), ('no_account', 'Account Does Not Exist'), ('invalid_pin', 'Invalid Pin'), ('archived', 'Archived')], default='pending', max_length=100)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_number', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('send_invoice', models.BooleanField(default=False)),
                ('pk_invoice_number', models.CharField(blank=True, max_length=5, null=True)),
                ('us_invoice_number', models.CharField(blank=True, max_length=5, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('depositor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.CharField(default='products', max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('additional_months', models.IntegerField(default=0)),
                ('dynamic_checkout_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_manual', models.BooleanField(default=False)),
                ('webhook_called', models.BooleanField(default=False)),
                ('old_payments', models.IntegerField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
