# Generated by Django 4.1.5 on 2023-09-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0045_new_al_nafi_payments_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='alnafi_payment',
            name='erp_lead',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
