# Generated by Django 4.1.5 on 2023-09-28 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0046_alnafi_payment_erp_lead'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='new_al_nafi_payments',
    #         name='customer_id',
    #     ),
    # ]
