# Generated by Django 4.1.5 on 2023-09-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0047_remove_new_al_nafi_payments_customer_id'),
    ]

    # operations = [
    #     migrations.DeleteModel(
    #         name='New_Al_Nafi_Payments',
    #     ),
    # ]
