# Generated by Django 4.1.5 on 2023-10-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0049_new_alnafi_payments'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='new_alnafi_payments',
    #         name='orderId',
    #         field=models.CharField(blank=True, max_length=255, null=True, unique=True),
    #     ),
    # ]
