# Generated by Django 4.1.5 on 2023-10-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0050_alter_new_alnafi_payments_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_alnafi_payments',
            name='orderId',
            field=models.CharField(default='nodata', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
