# Generated by Django 4.1.5 on 2023-10-12 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_alter_new_alnafi_product_alnafi_product_id_and_more'),
        ('payment', '0052_remove_main_payment_product_main_payment_product'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='main_payment',
        #     name='product',
        # ),
        migrations.AddField(
            model_name='main_payment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_payments', to='products.main_product'),
        ),
    ]
