# Generated by Django 4.1.5 on 2023-10-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0054_remove_main_payment_product_main_payment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alnafi_payment',
            name='product_name',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='easypaisa_payment',
            name='product_name',
            field=models.JSONField(blank=True, null=True),
        ),
        # migrations.AlterField(
        #     model_name='new_alnafi_payments',
        #     name='orderId',
        #     field=models.CharField(max_length=255),
        # ),
        migrations.AlterField(
            model_name='stripe_payment',
            name='product_name',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_ipg_payment',
            name='product_name',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='product_name',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
