# Generated by Django 4.1.5 on 2023-10-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0055_alter_alnafi_payment_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubl_manual_payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
