# Generated by Django 4.1.5 on 2024-01-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0086_main_product_discount_applied_pkr_and_more'),
        ('payment', '0104_new_alnafi_payments_new_alnafi_unpaid_and_more'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='New_Al_Nafi_Payments',
        # ),
        migrations.DeleteModel(
            name='New_ALnafi_Unpaid',
        ),
        # migrations.AddField(
        #     model_name='main_payment',
        #     name='product',
        #     field=models.ManyToManyField(blank=True, related_name='product_payments', to='products.main_product'),
        # ),
    ]
