# Generated by Django 4.1.5 on 2023-06-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newsletter_erp_lead_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
