# Generated by Django 4.1.5 on 2023-07-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_alter_newsletter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(default='no email', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
