# Generated by Django 4.1.5 on 2023-11-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_alter_newsletter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
