# Generated by Django 4.1.5 on 2024-01-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=101, null=True)),
                ('product', models.CharField(blank=True, max_length=101, null=True)),
                ('amount', models.CharField(blank=True, max_length=101, null=True)),
                ('lead_creator', models.CharField(blank=True, max_length=101, null=True)),
                ('al_baseer_verify', models.CharField(blank=True, max_length=50, null=True)),
                ('crm_verify', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
