# Generated by Django 4.1.5 on 2024-01-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_commissions', '0002_daily_lead_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
