# Generated by Django 4.1.5 on 2024-01-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_commissions', '0005_daily_lead_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_lead',
            name='source',
            field=models.CharField(blank=True, max_length=101, null=True),
        ),
    ]
