# Generated by Django 4.1.5 on 2024-01-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_commissions', '0006_daily_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_lead',
            name='renewal',
            field=models.CharField(blank=True, max_length=101, null=True),
        ),
    ]
