# Generated by Django 4.1.5 on 2024-01-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_commissions', '0007_daily_lead_renewal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_lead',
            old_name='al_baseer_verify',
            new_name='manager_approval',
        ),
        migrations.RenameField(
            model_name='daily_lead',
            old_name='crm_verify',
            new_name='manager_approval_crm',
        ),
        migrations.AddField(
            model_name='daily_lead',
            name='veriification_cfo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
