# Generated by Django 4.1.5 on 2024-02-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_commissions', '0013_daily_lead_completely_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_sales_support',
            name='completely_verified',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
