# Generated by Django 4.1.5 on 2024-02-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_commissions', '0014_daily_sales_support_completely_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_lead',
            name='paid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
