# Generated by Django 4.1.5 on 2024-02-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_commissions', '0015_daily_lead_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deleted_Daily_lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_id', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=101, null=True)),
                ('product', models.CharField(blank=True, max_length=101, null=True)),
                ('plan', models.CharField(blank=True, max_length=101, null=True)),
                ('renewal', models.CharField(blank=True, max_length=101, null=True)),
                ('is_exam_fee', models.CharField(blank=True, max_length=101, null=True)),
                ('amount', models.CharField(blank=True, max_length=101, null=True)),
                ('source', models.CharField(blank=True, max_length=101, null=True)),
                ('lead_creator', models.CharField(blank=True, max_length=101, null=True)),
                ('manager_approval', models.CharField(blank=True, max_length=50, null=True)),
                ('manager_approval_crm', models.CharField(blank=True, max_length=50, null=True)),
                ('veriification_cfo', models.CharField(blank=True, max_length=50, null=True)),
                ('support', models.CharField(blank=True, max_length=50, null=True)),
                ('completely_verified', models.CharField(blank=True, max_length=50, null=True)),
                ('paid', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
