# Generated by Django 4.1.5 on 2024-03-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_commissions', '0018_daily_lead_is_comission'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_sales_support',
            name='is_comission',
            field=models.BooleanField(default=False),
        ),
    ]
