# Generated by Django 4.1.5 on 2024-03-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_commissions', '0019_daily_sales_support_is_comission'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleted_daily_lead',
            name='is_comission',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deleted_daily_sales_support',
            name='is_comission',
            field=models.BooleanField(default=True),
        ),
    ]
