# Generated by Django 4.1.5 on 2023-08-16 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0049_alter_marketing_pkr_form_financial_sponsorship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(max_length=50)),
                ('review', models.TextField(blank=True, max_length=250, null=True)),
                ('course', models.CharField(blank=True, max_length=1000, null=True)),
                ('track', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('working', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_feedbacks', to='user.main_user')),
            ],
        ),
    ]
