# Generated by Django 4.1.5 on 2023-08-16 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_track_includedcourses'),
        ('feedback', '0004_remove_feedback_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.course'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.track'),
        ),
    ]
