# Generated by Django 4.1.5 on 2023-08-16 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_alter_feedback_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=255, null=True)),
                ('course_name', models.CharField(max_length=255, null=True)),
                ('question_answer', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=255)),
                ('question_answer', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbackquestion')),
            ],
        ),
    ]
