# Generated by Django 4.1.5 on 2023-06-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatwoot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatwooruser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatwooruser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
