# Generated by Django 4.1.5 on 2023-07-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatwoot', '0002_chatwooruser_city_chatwooruser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatwooruser',
            name='email',
            field=models.EmailField(default='created without email', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
