# Generated by Django 4.1.5 on 2023-08-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatwoot', '0004_agents_conversations_inbox_chatwooruser_inbox'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agents',
            new_name='Agent',
        ),
        migrations.RenameModel(
            old_name='Conversations',
            new_name='Conversation',
        ),
    ]
