# Generated by Django 4.1.5 on 2023-08-03 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatwoot', '0005_rename_agents_agent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatwoorUser',
            new_name='ChatwootUser',
        ),
    ]
