# Generated by Django 4.1.5 on 2023-08-03 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatwoot', '0006_rename_chatwooruser_chatwootuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatwootUser',
            new_name='Contacts',
        ),
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name_plural': 'Agents'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name_plural': 'Conversations'},
        ),
        migrations.AlterModelOptions(
            name='inbox',
            options={'verbose_name_plural': 'Inboxes'},
        ),
    ]
