# Generated by Django 4.1.5 on 2023-08-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatwoot', '0007_rename_chatwootuser_contacts_alter_agent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
