# Generated by Django 4.1.5 on 2023-08-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatwoot', '0008_alter_contacts_email_alter_contacts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
