# Generated by Django 4.1.5 on 2023-08-03 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatwoot', '0009_alter_contacts_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='erp_lead_id',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='phone',
        ),
        migrations.AddField(
            model_name='conversation',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_conversations', to='chatwoot.agent'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='channel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='chatwoot.contacts'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='inbox',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_conversations', to='chatwoot.inbox'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
