# Generated by Django 4.1.5 on 2023-08-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatwoot', '0010_remove_conversation_city_remove_conversation_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-08-03 15:00:00'),
            preserve_default=False,
        ),
    ]
