# Generated by Django 4.1.5 on 2023-08-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatwoot', '0011_alter_conversation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
