# Generated by Django 4.1.5 on 2023-09-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllSecretsApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('api_key', models.CharField(max_length=200, unique=True)),
                ('secret_key', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LastSecretApiUsing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('turn_number', models.IntegerField(default=1)),
                ('api_key', models.CharField(max_length=200, unique=True)),
                ('secret_key', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
