# Generated by Django 4.1.5 on 2023-09-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_api', '0002_allsecretsapi_turn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allsecretsapi',
            name='turn_number',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
