# Generated by Django 4.1.5 on 2023-06-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('Application', 'Application'), ('Server', 'Server'), ('Database', 'Database'), ('Other', 'Other')], max_length=100)),
                ('scan_date', models.DateTimeField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=100)),
                ('remediation', models.TextField()),
                ('scan_progress', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=100)),
                ('testing_method', models.CharField(choices=[('Auto', 'Auto'), ('Manual', 'Manual'), ('Auto&Manual', 'Auto&Manual')], max_length=100)),
                ('target', models.CharField(choices=[('IP', 'IP'), ('Domain', 'Domain'), ('CIDR', 'CIDR')], max_length=100)),
                ('http_or_https', models.CharField(choices=[('HTTP', 'HTTP'), ('HTTPS', 'HTTPS')], max_length=100)),
                ('application_type', models.CharField(choices=[('External', 'External'), ('Internal', 'Internal')], max_length=100)),
                ('findings_and_recommendations', models.TextField()),
            ],
        ),
    ]
