# Generated by Django 4.1.5 on 2023-06-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_scan_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='scan_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
