# Generated by Django 4.1.5 on 2023-06-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_scan_scan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='file_uploads/'),
        ),
        migrations.AddField(
            model_name='scan',
            name='poc',
            field=models.ImageField(blank=True, null=True, upload_to='poc_uploads/'),
        ),
    ]
