# Generated by Django 4.1.5 on 2023-06-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_scan_file_upload_scan_poc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/security/file_uploads'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='poc',
            field=models.ImageField(blank=True, null=True, upload_to='media/securitypoc_uploads/'),
        ),
    ]
