# Generated by Django 4.1.5 on 2023-06-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_alter_scan_file_upload_alter_scan_poc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='scan_date',
            field=models.DateTimeField(),
        ),
    ]
