# Generated by Django 4.1.5 on 2023-06-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_alter_scan_scan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='application_type',
            field=models.CharField(blank=True, choices=[('External', 'External'), ('Internal', 'Internal')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='findings_and_recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='http_or_https',
            field=models.CharField(blank=True, choices=[('HTTP', 'HTTP'), ('HTTPS', 'HTTPS')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='remediation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_progress',
            field=models.CharField(blank=True, choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(blank=True, choices=[('Application', 'Application'), ('Server', 'Server'), ('Database', 'Database'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='severity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='target',
            field=models.CharField(blank=True, choices=[('IP', 'IP'), ('Domain', 'Domain'), ('CIDR', 'CIDR')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='testing_method',
            field=models.CharField(blank=True, choices=[('Auto', 'Auto'), ('Manual', 'Manual'), ('Auto&Manual', 'Auto&Manual')], max_length=100, null=True),
        ),
    ]
