# Generated by Django 4.1.5 on 2023-06-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_alter_scan_application_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/security/file_uploads/'),
        ),
    ]
