# Generated by Django 4.1.5 on 2023-06-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_comment_alter_scan_file_upload_alter_scan_poc_reply_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
        migrations.AlterModelOptions(
            name='scan',
            options={'verbose_name_plural': 'Scans'},
        ),
    ]
