# Generated by Django 4.1.5 on 2023-06-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0013_rename_post_comment_scan_remove_comment_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='status',
            field=models.CharField(default='Idol', max_length=100),
        ),
    ]
