# Generated by Django 4.1.5 on 2023-07-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0015_remove_scan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='findings_and_recommendations',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='http_or_https',
        ),
        migrations.AddField(
            model_name='scan',
            name='target_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
