# Generated by Django 4.1.5 on 2023-07-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0017_department_remove_comment_user_comment_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='file_upload_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='poc_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
