# Generated by Django 4.1.5 on 2023-07-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0017_department_remove_comment_user_comment_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='assigned_to',
        ),
    ]
