# Generated by Django 4.1.5 on 2023-07-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0019_scan_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
