# Generated by Django 4.1.5 on 2023-07-21 10:56

from django.db import migrations, models
import security.models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0021_remove_scan_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='poc',
            field=models.FileField(blank=True, null=True, storage=security.models.YourS3Storage(), upload_to='media/security/poc_uploads'),
        ),
    ]
