# Generated by Django 4.1.5 on 2023-08-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0022_alter_scan_poc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='scan',
            name='assigned_to',
            field=models.ManyToManyField(related_name='department_scans', to='security.department'),
        ),
    ]
