# Generated by Django 4.1.5 on 2023-08-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0026_alter_scan_poc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='department_scans', to='security.department'),
        ),
    ]
