# Generated by Django 4.1.5 on 2023-08-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0027_alter_scan_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='assigned_to',
            field=models.ManyToManyField(related_name='department_scans', to='security.department'),
        ),
    ]
