# Generated by Django 4.1.5 on 2023-03-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IslamicAcademyUser',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('is_paying_customer', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('role', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.JSONField()),
            ],
            options={
                'verbose_name': 'Islamic Academy User',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name': 'Al-Nafi User'},
        ),
    ]
