# Generated by Django 4.1.5 on 2023-03-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_islamicacademyuser_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islamicacademyuser',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
