# Generated by Django 4.1.5 on 2023-03-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_islamicacademyuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islamicacademyuser',
            name='is_paying_customer',
            field=models.BooleanField(),
        ),
    ]
