# Generated by Django 4.1.5 on 2023-04-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alnafi_user_islamicacademy_user_delete_alnafiuser_and_more'),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='User',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('password', models.CharField(max_length=128, verbose_name='password')),
    #             ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
    #             ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
    #             ('name', models.CharField(max_length=200)),
    #             ('is_active', models.BooleanField(default=True)),
    #             ('is_admin', models.BooleanField(default=False)),
    #             ('created_at', models.DateTimeField(auto_now_add=True)),
    #             ('updated_at', models.DateTimeField(auto_now=True)),
    #         ],
    #         options={
    #             'abstract': False,
    #         },
    #     ),
    # ]
