# Generated by Django 4.1.5 on 2023-04-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
