# Generated by Django 4.1.5 on 2023-04-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_navbarlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alnafi_user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alnafi_user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alnafi_user',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
