# Generated by Django 4.1.5 on 2023-04-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_alnafi_user_address_alter_alnafi_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarlink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='navbar_images'),
        ),
    ]
