# Generated by Django 4.1.5 on 2023-04-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_navbarlink_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarlink',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
