# Generated by Django 4.1.5 on 2023-05-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_main_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_user',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
