# Generated by Django 4.1.5 on 2023-05-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_main_user_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_user',
            name='is_paying_customer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
