# Generated by Django 4.1.5 on 2023-05-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_main_user_is_paying_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_user',
            name='is_paying_customer',
            field=models.BooleanField(default=False),
        ),
    ]
