# Generated by Django 4.1.5 on 2023-06-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_user_department_user_phone_alter_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSWFormRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hear_about_us', models.CharField(blank=True, max_length=100, null=True)),
                ('know_about_alnafi', models.CharField(default='No', max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('study_field', models.CharField(blank=True, max_length=255, null=True)),
                ('email_address', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=100, null=True)),
                ('university_name', models.CharField(blank=True, max_length=255, null=True)),
                ('level_of_education', models.CharField(blank=True, max_length=100, null=True)),
                ('title_of_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('user_status_of_PSW', models.CharField(blank=True, max_length=100, null=True)),
                ('student_visa_expiry', models.CharField(blank=True, max_length=100, null=True)),
                ('skillset', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('move_another_eu_country', models.CharField(blank=True, max_length=100, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='media/psw_form/resumes')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
