# Generated by Django 4.1.5 on 2023-06-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_pswformrecords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pswformrecords',
            old_name='move_another_eu_country',
            new_name='move_another_country',
        ),
    ]
