# Generated by Django 4.1.5 on 2023-06-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_pswformrecords_leaving_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pswformrecords',
            old_name='leaving_country',
            new_name='living_country',
        ),
    ]
