# Generated by Django 4.1.5 on 2023-06-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_main_user_erp_lead_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alnafi_user',
            name='erp_lead_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='islamicacademy_user',
            name='erp_lead_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
