# Generated by Django 4.1.5 on 2023-06-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_rename_contact_number_pswformrecords_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pswformrecords',
            old_name='know_about_alnafi',
            new_name='yknow_about_alnafi',
        ),
    ]
