# Generated by Django 4.1.5 on 2023-06-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_rename_know_about_alnafi_pswformrecords_yknow_about_alnafi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pswformrecords',
            old_name='yknow_about_alnafi',
            new_name='know_about_alnafi',
        ),
    ]
