# Generated by Django 4.1.5 on 2023-06-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_rename_yknow_about_alnafi_pswformrecords_know_about_alnafi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pswformrecords',
            name='erp_lead_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
