# Generated by Django 4.1.5 on 2023-06-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_pswformrecords_erp_lead_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_user',
            name='internal_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
