# Generated by Django 4.1.5 on 2023-06-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_main_user_internal_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='alnafi_user',
            name='login_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
