# Generated by Django 4.1.5 on 2023-07-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_alter_alnafi_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alnafi_user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
