# Generated by Django 4.1.5 on 2023-07-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_alter_alnafi_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alnafi_user',
            name='email',
            field=models.EmailField(default='no email', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
