# Generated by Django 4.1.5 on 2023-07-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_alter_alnafi_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alnafi_user',
            name='created_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
