# Generated by Django 4.1.5 on 2023-07-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_alter_alnafi_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islamicacademy_user',
            name='email',
            field=models.EmailField(default='noemail', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
