# Generated by Django 4.1.5 on 2023-07-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_alter_islamicacademy_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing_PKR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('study_field', models.CharField(blank=True, max_length=255, null=True)),
                ('level_of_education', models.CharField(blank=True, max_length=100, null=True)),
                ('university_name', models.CharField(blank=True, max_length=255, null=True)),
                ('title_of_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('move_another_country', models.CharField(blank=True, max_length=100, null=True)),
                ('skillset', models.CharField(blank=True, max_length=255, null=True)),
                ('skillset_budget', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('financial_sponsorship', models.BooleanField(default=False)),
                ('resume', models.FileField(blank=True, null=True, upload_to='media/marketing_pkr/resumes')),
                ('communication', models.CharField(blank=True, max_length=255, null=True)),
                ('know_about_alnafi', models.CharField(default='No', max_length=100)),
                ('hear_about_us', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('erp_lead_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
