# Generated by Django 4.1.5 on 2023-07-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_alter_alnafi_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alnafi_user',
            name='created_at',
            field=models.CharField(default='nodate', max_length=100),
            preserve_default=False,
        ),
    ]
