# Generated by Django 4.1.5 on 2023-07-27 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_marketing_pkr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marketing_PKR',
            new_name='Marketing_PKR_Form',
        ),
    ]
