# Generated by Django 4.1.5 on 2023-07-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_rename_marketing_pkr_marketing_pkr_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing_pkr_form',
            name='know_about_alnafi',
            field=models.BooleanField(default=False),
        ),
    ]
