# Generated by Django 4.1.5 on 2023-07-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_alter_marketing_pkr_form_know_about_alnafi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing_pkr_form',
            name='financial_sponsorship',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='marketing_pkr_form',
            name='know_about_alnafi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
