# Generated by Django 4.1.5 on 2023-08-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_alter_marketing_pkr_form_financial_sponsorship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moc_Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=30, null=True)),
                ('isAffiliate', models.BooleanField(default=False)),
                ('how_did_you_hear_about_us', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliate_code', models.CharField(blank=True, max_length=255, null=True)),
                ('isMentor', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('login_source', models.CharField(blank=True, max_length=100, null=True)),
                ('erp_lead_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'MOC Leads',
                'managed': True,
            },
        ),
    ]
