# Generated by Django 4.1.5 on 2023-08-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_moc_leads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moc_leads',
            options={'managed': True, 'verbose_name': 'MOC Lead'},
        ),
    ]
