# Generated by Django 4.1.5 on 2023-08-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_alter_moc_leads_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moc_leads',
            old_name='address',
            new_name='form',
        ),
        migrations.RenameField(
            model_name='moc_leads',
            old_name='affiliate_code',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='moc_leads',
            old_name='country',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='moc_leads',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='moc_leads',
            name='how_did_you_hear_about_us',
        ),
        migrations.RemoveField(
            model_name='moc_leads',
            name='isAffiliate',
        ),
        migrations.RemoveField(
            model_name='moc_leads',
            name='isMentor',
        ),
        migrations.RemoveField(
            model_name='moc_leads',
            name='language',
        ),
        migrations.RemoveField(
            model_name='moc_leads',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='moc_leads',
            name='login_source',
        ),
        migrations.RemoveField(
            model_name='moc_leads',
            name='username',
        ),
        migrations.RemoveField(
            model_name='moc_leads',
            name='verification_code',
        ),
        migrations.AlterField(
            model_name='moc_leads',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
