# Generated by Django 4.1.5 on 2023-09-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_new_alnafi_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new_alnafi_user',
            options={'managed': True, 'verbose_name': 'New Al-Nafi User'},
        ),
        migrations.RemoveField(
            model_name='new_alnafi_user',
            name='profile_pic',
        ),
    ]
