# Generated by Django 4.1.5 on 2023-09-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_alter_new_alnafi_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moc_leads',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
