# Generated by Django 4.1.5 on 2023-09-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_new_alnafi_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_alnafi_user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='new_alnafi_user',
            name='student_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
