# Generated by Django 4.1.5 on 2023-09-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_moc_leads_interest_moc_leads_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alnafi_user',
            name='erp_lead_id',
        ),
    ]
