# Generated by Django 4.1.5 on 2023-10-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0065_alter_moc_leads_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='alnafi_user',
            name='academy_demo_access',
            field=models.BooleanField(default=False),
        ),
    ]
