# Generated by Django 4.1.5 on 2023-10-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0066_alnafi_user_academy_demo_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_user',
            name='academy_demo_access',
            field=models.BooleanField(default=False),
        ),
    ]
