# Generated by Django 4.1.5 on 2023-10-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0067_main_user_academy_demo_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='alnafi_user',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alnafi_user',
            name='form',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
