# Generated by Django 4.1.5 on 2023-10-26 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0068_alnafi_user_assigned_date_alnafi_user_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moc_leads',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='moc_leads',
            old_name='source',
            new_name='login_source',
        ),
    ]
