# Generated by Django 4.1.5 on 2023-11-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0069_rename_full_name_moc_leads_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moc_leads',
            name='assigned_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
