# Generated by Django 4.1.5 on 2023-11-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0070_moc_leads_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='moc_leads',
            name='advert',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
