# Generated by Django 4.1.5 on 2023-12-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0071_moc_leads_advert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alnafi_user',
            name='advert',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
