# Generated by Django 4.1.5 on 2023-12-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0072_alnafi_user_advert'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('cnic_no', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('martial_status', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number_1', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number_2', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_resume', models.FileField(blank=True, null=True, upload_to='')),
                ('your_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('position_uplied_for', models.CharField(blank=True, max_length=100, null=True)),
                ('work_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('date_you_can_start', models.CharField(blank=True, max_length=100, null=True)),
                ('present_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('desired_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('descipline', models.CharField(blank=True, max_length=100, null=True)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('marks_obtained', models.CharField(blank=True, max_length=100, null=True)),
                ('total_marks', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date_job', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date_job', models.CharField(blank=True, max_length=100, null=True)),
                ('major_projects', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.CharField(blank=True, max_length=100, null=True)),
                ('referance_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address_city', models.CharField(blank=True, max_length=100, null=True)),
                ('referance_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('relationship_with', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
