# Generated by Django 4.1.5 on 2023-12-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0073_cvforms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvforms',
            old_name='academic_qualification',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='cvforms',
            old_name='address_city',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='cvforms',
            old_name='company',
            new_name='refrences',
        ),
        migrations.RenameField(
            model_name='cvforms',
            old_name='date_you_can_start',
            new_name='work_history',
        ),
        migrations.RemoveField(
            model_name='cvforms',
            name='descipline',
        ),
        migrations.RemoveField(
            model_name='cvforms',
            name='desired_salary',
        ),
        migrations.RemoveField(
            model_name='cvforms',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='cvforms',
            name='end_date_job',
        ),
        migrations.RemoveField(
            model_name='cvforms',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='cvforms',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='cvforms',
            name='major_projects',
        ),
        migrations.RemoveField(
            model_name='cvforms',
            name='marks_obtained',
        ),
        migrations.RemoveField(
            model_name='cvforms',
            name='position_uplied_for',
        ),
        migrations.RemoveField(
            model_name='cvforms',
            name='present_salary',
        ),
        migrations.RemoveField(
            model_name='cvforms',
            name='referance_name',
        ),
        migrations.RemoveField(
            model_name='cvforms',
            name='referance_phone',
        ),
        migrations.RemoveField(
            model_name='cvforms',
            name='relationship_with',
        ),
        migrations.RemoveField(
            model_name='cvforms',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='cvforms',
            name='start_date_job',
        ),
        migrations.RemoveField(
            model_name='cvforms',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='cvforms',
            name='work_experience',
        ),
        migrations.AlterField(
            model_name='cvforms',
            name='updated_resume',
            field=models.FileField(blank=True, null=True, upload_to='cv/resume_uploads'),
        ),
        migrations.AlterField(
            model_name='cvforms',
            name='your_picture',
            field=models.ImageField(blank=True, null=True, upload_to='cv/profile_pic'),
        ),
    ]
