# Generated by Django 4.1.5 on 2024-01-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0075_alter_cvforms_certificate_alter_cvforms_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_alnafi_user',
            name='how_did_you_hear_about_us',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
