# Generated by Django 4.1.5 on 2024-02-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0076_new_alnafi_user_how_did_you_hear_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='moc_leads',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
