# Generated by Django 4.1.5 on 2023-03-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_alnafiproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alnafiproduct',
            options={'managed': False, 'verbose_name': 'Al-Nafi Product'},
        ),
    ]
