# Generated by Django 4.1.5 on 2023-03-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_alnafiproduct_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alnafiproduct',
            options={'managed': True, 'verbose_name': 'Al-Nafi Product'},
        ),
    ]
