# Generated by Django 4.1.5 on 2023-03-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_alnafiproduct_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alnafiproduct',
            table=None,
        ),
    ]
