# Generated by Django 4.1.5 on 2023-03-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_islamicacademyproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='islamicacademyproduct',
            name='regular_price',
        ),
        migrations.RemoveField(
            model_name='islamicacademyproduct',
            name='sale_price',
        ),
    ]
