# Generated by Django 4.1.5 on 2023-03-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_islamicacademyproduct_regular_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islamicacademyproduct',
            name='slug',
            field=models.CharField(max_length=255),
        ),
    ]
