# Generated by Django 4.1.5 on 2023-03-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_islamicacademyproduct_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islamicacademyproduct',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
