# Generated by Django 4.1.5 on 2023-03-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_islamicacademyproduct_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='alnafiproduct',
            name='allow_coupon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alnafiproduct',
            name='amount_gbp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='alnafiproduct',
            name='courses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alnafiproduct',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='alnafiproduct',
            name='is_certificate_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='amount_pkr',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='bundle_Ids',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='language',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='legacy_available',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='legacy_fee_pkr',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='legacy_fee_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='lms_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='old_amount_pkr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='old_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='plan',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='productSlug',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='product_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='qarz_fee_pkr',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='qarz_fee_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
