# Generated by Django 4.1.5 on 2023-03-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_alnafiproduct_legacy_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alnafiproduct',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
