# Generated by Django 4.1.5 on 2023-03-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_alnafiproduct_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alnafiproduct',
            name='amount_gbp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='amount_pkr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='amount_usd',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='legacy_fee_pkr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='legacy_fee_usd',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='old_amount_pkr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='old_amount_usd',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='qarz_fee_pkr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='qarz_fee_usd',
            field=models.FloatField(null=True),
        ),
    ]
