# Generated by Django 4.1.5 on 2023-03-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_alnafiproduct_amount_gbp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alnafiproduct',
            name='amount_gbp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='amount_pkr',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='legacy_fee_pkr',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='legacy_fee_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='old_amount_pkr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='old_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='qarz_fee_pkr',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='qarz_fee_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
