# Generated by Django 4.1.5 on 2023-03-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_alnafiproduct_allow_coupon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alnafiproduct',
            name='allow_coupon',
        ),
        migrations.RemoveField(
            model_name='alnafiproduct',
            name='amount_gbp',
        ),
        migrations.RemoveField(
            model_name='alnafiproduct',
            name='amount_pkr',
        ),
        migrations.RemoveField(
            model_name='alnafiproduct',
            name='amount_usd',
        ),
        migrations.RemoveField(
            model_name='alnafiproduct',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='alnafiproduct',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='alnafiproduct',
            name='has_legacy_version',
        ),
        migrations.RemoveField(
            model_name='alnafiproduct',
            name='is_certificate_product',
        ),
        migrations.RemoveField(
            model_name='alnafiproduct',
            name='legacy_available',
        ),
        migrations.RemoveField(
            model_name='alnafiproduct',
            name='legacy_fee_pkr',
        ),
        migrations.RemoveField(
            model_name='alnafiproduct',
            name='legacy_fee_usd',
        ),
        migrations.RemoveField(
            model_name='alnafiproduct',
            name='lms_id',
        ),
        migrations.RemoveField(
            model_name='alnafiproduct',
            name='old_amount_pkr',
        ),
        migrations.RemoveField(
            model_name='alnafiproduct',
            name='old_amount_usd',
        ),
        migrations.RemoveField(
            model_name='alnafiproduct',
            name='qarz_fee_pkr',
        ),
        migrations.RemoveField(
            model_name='alnafiproduct',
            name='qarz_fee_usd',
        ),
        migrations.RemoveField(
            model_name='alnafiproduct',
            name='qarz_product',
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='bundle_Ids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='plan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='productSlug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alnafiproduct',
            name='product_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
