# Generated by Django 4.1.5 on 2023-03-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_alnafiproduct_allow_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alnafiproduct',
            name='amount_pkr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='alnafiproduct',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
