# Generated by Django 4.1.5 on 2023-03-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alnafiproduct_allow_coupon_alnafiproduct_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alnafiproduct',
            name='courses',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
