# Generated by Django 4.1.5 on 2023-03-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alnafiproduct_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='IslamicAcademy_Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('simple', 'Simple'), ('variable', 'Variable')], default='simple', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock_status', models.CharField(default='instock', max_length=20)),
            ],
            options={
                'verbose_name': 'Islamic Academy Product',
                'managed': True,
            },
        ),
        migrations.RenameModel(
            old_name='AlnafiProduct',
            new_name='Alnafi_Product',
        ),
        migrations.DeleteModel(
            name='IslamicAcademyProduct',
        ),
        migrations.RenameField(
            model_name='alnafi_product',
            old_name='productSlug',
            new_name='product_slug',
        ),
    ]
