# Generated by Django 4.1.5 on 2023-04-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_islamicacademy_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('AL-NAFI', 'Al-Nafi'), ('ISLAMIC-ACADEMY', 'Islamic Academy')], max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('product_slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_type', models.CharField(max_length=50)),
                ('product_plan', models.CharField(max_length=50)),
                ('amount_pkr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_language', models.CharField(max_length=50)),
                ('allow_coupon', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Main Product',
                'managed': True,
            },
        ),
    ]
