# Generated by Django 4.1.5 on 2023-05-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_main_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_product',
            name='amount_gbp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='main_product',
            name='bundle_ids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main_product',
            name='courses',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main_product',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main_product',
            name='has_legacy_version',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='main_product',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main_product',
            name='is_certificate_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='main_product',
            name='legacy_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='main_product',
            name='legacy_fee_pkr',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='main_product',
            name='legacy_fee_usd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='main_product',
            name='lms_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main_product',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='main_product',
            name='old_amount_pkr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='main_product',
            name='old_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='main_product',
            name='qarz_fee_pkr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main_product',
            name='qarz_fee_usd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main_product',
            name='qarz_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='main_product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='main_product',
            name='stock_status',
            field=models.CharField(default='instock', max_length=20),
        ),
        migrations.AlterField(
            model_name='main_product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='main_product',
            name='product_language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
