# Generated by Django 4.1.5 on 2023-05-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_main_product_amount_gbp_main_product_bundle_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_product',
            name='source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
