# Generated by Django 4.1.5 on 2023-05-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_main_product_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
