# Generated by Django 4.1.5 on 2023-07-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_main_product_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
