# Generated by Django 4.1.5 on 2023-08-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_course_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='includedCourses',
        ),
    ]
