# Generated by Django 4.1.5 on 2023-09-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_track_includedcourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Alnafi_Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type', models.CharField(blank=True, max_length=255, null=True)),
                ('product_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('plan', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('bundle_Ids', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_pkr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_gbp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('old_amount_pkr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('old_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('legacy_fee_pkr', models.IntegerField(blank=True, default=0, null=True)),
                ('legacy_fee_usd', models.IntegerField(blank=True, default=0, null=True)),
                ('legacy_available', models.BooleanField(default=False)),
                ('qarz_product', models.BooleanField(default=False)),
                ('qarz_fee_pkr', models.IntegerField(blank=True, null=True)),
                ('qarz_fee_usd', models.IntegerField(blank=True, null=True)),
                ('lms_id', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('has_legacy_version', models.BooleanField(default=False)),
                ('is_certificate_product', models.BooleanField(default=False)),
                ('allow_coupon', models.BooleanField(default=False)),
                ('courses', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'New Al-Nafi Product',
                'managed': True,
            },
        ),
    ]
