# Generated by Django 4.1.5 on 2023-10-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_main_product_discount_applied_pkr_and_more'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='main_product',
    #         name='discount_applied_pkr',
    #         field=models.CharField(blank=True, max_length=100, null=True),
    #     ),
    #     migrations.AddField(
    #         model_name='main_product',
    #         name='discount_applied_usd',
    #         field=models.CharField(blank=True, max_length=100, null=True),
    #     ),
    #     migrations.AddField(
    #         model_name='main_product',
    #         name='duration',
    #         field=models.CharField(blank=True, max_length=50, null=True),
    #     ),
    # ]
